version: '3.6'

services:
  postgres:
    container_name: mina-bridge-${NODE_ENV}-postgres
    image: postgres:15.3-alpine3.18
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mina-bridge
    networks:
      myNetwork:

volumes:
  postgresData:
networks:
  myNetwork:
    name: minaBridgeNetwork${NODE_ENV}
