services:
  api:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run migration:run-dist && npm run start:prod;"
    tty: true
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  crawl-bridge-evm:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console crawl-eth-bridge-contract"
    tty: true
    restart: always

    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  sender-evm:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console sender-eth-bridge-unlock"
    tty: true
    restart: always

    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  crawl-bridge-mina:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console crawl-mina-bridge-contract"
    tty: true
    restart: always

    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  crawl-token-mina:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console crawl-mina-token-contract"
    tty: true
    restart: always

    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  sender-mina:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console sender-mina-bridge-unlock"
    tty: true
    restart: always
    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  get-price-token:
    image: mina-bridge:1.0.0
    command: >
      sh -c "npm run console get-price-token"
    tty: true
    restart: always
    depends_on:
      - postgres
    networks:
      - myNetwork
    user: node
  postgres:
    container_name: mina-bridge-${NODE_ENV}-postgres
    image: postgres:15.3-alpine3.18
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgresData:/var/lib/postgresql/data
    command: -p ${DB_PORT}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mina-bridge
    networks:
      myNetwork:


volumes:
  postgresData:
networks:
  myNetwork:
    name: minaBridgeNetwork${NODE_ENV}
