export enum EError {
  OTHER_SYSTEM_ERROR = 'OTHER_SYSTEM_ERROR',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  DUPLICATED_ACTION = 'DUPLICATED_ACTION',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_EMAIL_OR_PASS = 'WRONG_EMAIL_OR_PASS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  OVER_DAILY_QUOTA = 'OVER_DAILY_QUOTA',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  NETWORK_FAILED = 'NETWORK_FAILED',
}
