export enum EError {
  OTHER_SYSTEM_ERROR = 'OTHER_SYSTEM_ERROR',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_EMAIL_OR_PASS = 'WRONG_EMAIL_OR_PASS',
  INVALID_TOKEN = 'INVALID_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
