export const RPC_SERVICE_INJECT = 'RPC_SERVICE';
export const RPC_ETH_SERVICE_INJECT = 'RPC_ETH_SERVICE';
export const ETH_BRIDGE_ADDRESS_INJECT = 'ETH_BRIDGE_ADDRESS_INJECT';
export const ETH_BRIDGE_START_BLOCK_INJECT = 'ETH_BRIDGE_START_BLOCK_INJECT';
